### ISSUE TITLE
华为10.0闪退 

### ISSUE THREAD

**Issue by lovejhf** [taoweiji/MixPush#39]
Attempt to invoke interface method 'void com.mixpush.core.MixPushPassThroughReceiver.onReceiveMessage

**Comment by lovejhf** [comment]
透传的闪退 通知消息正常

**Comment by taoweiji** [comment]
可以提供完整的崩溃信息堆栈吗？

**Comment by lovejhf** [comment]
java.lang.RuntimeException: Unable to start service com.mixpush.huawei.UnifiedHmsMessageService@bb4188c with Intent { act=com.huawei.push.action.MESSAGING_EVENT pkg=xxx.xxx.xxx (has extras) }: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpush.core.MixPushPassThroughReceiver.onReceiveMessage(android.content.Context, com.mixpush.core.MixPushMessage)' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4683)
        at android.app.ActivityThread.access$2900(ActivityThread.java:296)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2259)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpush.core.MixPushPassThroughReceiver.onReceiveMessage(android.content.Context, com.mixpush.core.MixPushMessage)' on a null object reference
        at com.mixpush.core.DefaultPassThroughReceiver.onReceiveMessage(MixPushHandler.java:69)
        at com.mixpush.huawei.UnifiedHmsMessageService.onMessageReceived(UnifiedHmsMessageService.java:27)
        at com.huawei.hms.push.HmsMessageService.a(HmsMessageService.java:185)
        at com.huawei.hms.push.HmsMessageService.onStartCommand(HmsMessageService.java:131)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4663)
        at android.app.ActivityThread.access$2900(ActivityThread.java:296) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2259) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8178) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by taoweiji** [comment]
已经在2.1.0版本修复，非常感谢你的反馈
