### ISSUE TITLE
华为推送(后端)无法使用，报错：No appropriate protocol (protocol is disabled or cipher suites are inappropriate)

### ISSUE THREAD

**Issue by fzyzcjy** [taoweiji/MixPush#46]
```
No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
at com.huawei.push.messaging.HuaweiMessageClientImpl.sendRequest(HuaweiMessageClientImpl.java:144)
at com.huawei.push.messaging.HuaweiMessageClientImpl.send(HuaweiMessageClientImpl.java:76)
at com.huawei.push.messaging.HuaweiMessaging.sendMessage(HuaweiMessaging.java:134)
at com.huawei.push.messaging.HuaweiMessaging.sendMessage(HuaweiMessaging.java:86)
at ....mix_push_source.provider.HuaweiPushProvider.sendMessageToSingle(HuaweiPushProvider.java:41)
```

**Comment by taoweiji** [comment]
测试没有发现问题，当前已经更新最新的sdk，你尝试是否还存在问题
